springdoc:
  server.url: https://back.komirka.pp.ua

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://${DB_URL}/marketplace
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    jwt:
      header: Authorization
      secret: ${JWT_SECRET}
      expiration: 600000000
      token-time: 10
      refresh-token-time: 1000
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: ${MAIL_HOST}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 60000
