server:
  address: 0.0.0.0
  port: 8080


spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/database/project-changelogs.xml

cloudinary:
  name: ${CLOUD_NAME}
  key: ${API_KEY}
  secret: ${API_SECRET}

product:
  sizeListImage: 6
  disable:
    size: 6
  active:
    periodsDeadline: 30,60
  delete:
    periodDeadline: 180
    periodWarning: 5
  cron: 0 * * * * ?

mail:
  template:
    path:
      user: templates/msg_for_user.html

logging:
  level:
    root: INFO
    com:
      teamchallenge: DEBUG
  file:
    name: logs/komirka-back.log
    max-size: 10MB
    max-history: 5
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
console-appender:
  enabled: true
file-appender:
  enabled: true
