springdoc:
  server.url: http://ec2-3-79-99-48.eu-central-1.compute.amazonaws.com

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://marketplace.cqpznqxgmkio.eu-central-1.rds.amazonaws.com/marketplace
    username: postgres
    password: 9WBst4lg4udx5eS0VwPx
    driver-class-name: org.postgresql.Driver
