springdoc:
  server.url: http://localhost:${server.port}

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    jwt:
      header: Authorization
      secret: zPAWvmOTAxXaTKcGj8IzyITdYarTrAvazMw2YvJpkbw
      expiration: 600000000
      token-time: 10
      refresh-token-time: 1000
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 465
    username: 8007a8def7dfcc
    password: ae6ffc6d85c9cc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
