springdoc:
  server.url: http://localhost:${server.port}

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  security:
    jwt:
      header: Authorization
      secret: secret
      expiration: 600000
      token-time: 10
      refresh-token-time: 1000
