spring:
  datasource:
    url: jdbc:tc:postgresql:15.3://marketplace
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
