springdoc:
  server.url: http://ec2-3-79-99-48.eu-central-1.compute.amazonaws.com

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://${DB_URL}/marketplace
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    jwt:
      header: Authorization
      secret: ${JWT_SECRET}
      expiration: 600000
      token-time: 10
      refresh-token-time: 1000
