name: Marketplace CI/CD
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build Project
        run: mvn clean install
  package:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -  name: Build and push
         uses: docker/build-push-action@v4
         with:
           push: true
           tags:  ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE }}:latest
  deploy:
    needs: package
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}:latest
            ./remove_images.sh
            ./remove_container.sh marketplace-container
            docker run --name ${{ secrets.CONTAINER }} -d -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}:latest
